package com.unseen.portal;

import com.unseen.Config;
import com.unseen.HollowDimension;
import com.unseen.ModBlocks;
import com.unseen.UnseenMod;
import com.unseen.block.HollowPortalBlock;
import net.minecraft.block.BlockState;
import net.minecraft.block.Blocks;
import net.minecraft.entity.Entity;
import net.minecraft.server.world.ServerWorld;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.math.Direction;
import net.minecraft.world.World;

import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import java.util.UUID;

/**
 * Frames, ignition, and travel between the overworld and the Hollow.
 * <p>
 * Portals are not generated by worldgen. The Director places them near a player who is already under
 * pressure, which means they are discovered rather than searched for — you turn a corner in a cave you
 * have walked twice and there is a way in that was not there before. A portal, once placed, is
 * permanent, so the world accumulates them.
 */
public final class HollowPortal {
	/** Interior of the frame, in blocks. */
	public static final int WIDTH = 2;
	public static final int HEIGHT = 3;

	/** Ticks an entity must stand in the portal before it takes them. */
	private static final int DWELL_TICKS = 50;

	// Keyed on the entity rather than its UUID, and weak: a pig that brushes a portal and wanders off
	// must not leave an entry behind forever. UUID-keyed maps only ever got cleaned on player disconnect.
	private static final Map<Entity, Integer> DWELL = new java.util.WeakHashMap<>();
	private static final Map<Entity, Integer> COOLDOWN = new java.util.WeakHashMap<>();

	private HollowPortal() {
	}

	// --- Travel ---

	public static void onEntityInPortal(World world, Entity entity) {
		if (world.isClient || !(world instanceof ServerWorld serverWorld)) {
			return;
		}
		if (!entity.hasVehicle() && entity.getPassengerList().isEmpty() && entity.canUsePortals(false)) {
			tick(serverWorld, entity);
		}
	}

	private static void tick(ServerWorld world, Entity entity) {
		// Immersive Portals moves entities itself, seamlessly, and running our dwell-teleport as well
		// would yank the player a second time mid-transition — but only where it actually has a portal.
		// Standing down merely because the mod is installed is how every worldgen portal ended up inert:
		// those frames are built during chunk generation, which has no ServerWorld and so can never
		// spawn the view entity. Here we do have one, so make it now, and only defer if that worked.
		if (seamlessCovers(world, entity)) {
			return;
		}
		int cooling = COOLDOWN.getOrDefault(entity, 0);
		if (cooling > 0) {
			if (cooling <= 1) {
				COOLDOWN.remove(entity); // drop spent entries instead of leaving zeroes behind
			} else {
				COOLDOWN.put(entity, cooling - 1);
			}
			DWELL.remove(entity);
			return;
		}
		int dwelt = DWELL.merge(entity, 1, Integer::sum);
		if (dwelt < DWELL_TICKS) {
			return;
		}
		DWELL.remove(entity);
		COOLDOWN.put(entity, 200);
		travel(world, entity);
	}

	private static void travel(ServerWorld from, Entity entity) {
		boolean leaving = HollowDimension.isHollow(from);
		ServerWorld destination = leaving
				? from.getServer().getOverworld()
				: from.getServer().getWorld(HollowDimension.WORLD);
		if (destination == null) {
			UnseenMod.LOGGER.warn("The Hollow is not loaded; portal cannot take anyone through.");
			return;
		}

		// One-to-one coordinates, so the two worlds sit on top of each other. Getting lost in the Hollow
		// and getting lost at home are then the same problem, which is the point of it.
		int x = entity.getBlockPos().getX();
		int z = entity.getBlockPos().getZ();
		BlockPos landing = findLanding(destination, x, z);

		// A way back, built for them — but only once, and only into empty space.
		//
		// It used to build at landing.down(), which put the frame's interior through the very block
		// findLanding had just confirmed was solid ground, so the arriving entity was dropped into a
		// hole with nothing under it. The interior belongs at the landing itself, standing on that
		// ground. Arriving inside the frame is fine: the cooldown below stops it sending you straight
		// back, and a doorway is the right thing to arrive in.
		//
		// clearFor is the difference between building a way home and vandalising someone's house.
		// Coordinates are shared one-to-one between the worlds, so the spot you come back to is very
		// often somewhere you have already built.
		if (!hasPortalNear(destination, landing) && clearFor(destination, landing)) {
			buildFrame(destination, landing, Direction.Axis.X, true);
		}

		entity.teleport(destination, landing.getX() + 0.5, landing.getY(), landing.getZ() + 0.5,
				Set.of(), entity.getYaw(), entity.getPitch());
		COOLDOWN.put(entity, 200);
	}

	/** First standable spot scanning down from the top of the world. */
	private static BlockPos findLanding(ServerWorld world, int x, int z) {
		int top = world.getTopY(net.minecraft.world.Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, x, z);
		for (int y = Math.min(top + 1, world.getTopY() - 4); y > world.getBottomY() + 1; y--) {
			BlockPos pos = new BlockPos(x, y, z);
			if (world.getBlockState(pos.down()).isSolidBlock(world, pos.down())
					&& world.getBlockState(pos).isAir()
					&& world.getBlockState(pos.up()).isAir()) {
				return pos;
			}
		}
		return new BlockPos(x, 70, z);
	}

	// --- Frames ---

	/**
	 * Builds a frame with its bottom-centre at {@code base}, optionally lit.
	 *
	 * @return the position the portal occupies
	 */
	public static BlockPos buildFrame(ServerWorld world, BlockPos base, Direction.Axis axis, boolean lit) {
		buildFrameBlocks(world, base, axis, lit);
		if (lit) {
			ImmersivePortalsBridge.createSeamless(world, base, axis);
		}
		return base;
	}

	/**
	 * Just the blocks, through whatever world view the caller has.
	 * <p>
	 * Worldgen must come through here rather than {@link #buildFrame}, and must not hand us a
	 * {@code ServerWorld}: during chunk generation the region being built is not loaded as a chunk yet,
	 * so a {@code ServerWorld.setBlockState} blocks waiting for a chunk that is waiting on us, and the
	 * server deadlocks. The Immersive Portals view entity is skipped for the same reason — the portal
	 * block handles travel by itself, and the see-through view can be made later.
	 */
	public static BlockPos buildFrameBlocks(net.minecraft.world.ModifiableWorld world, BlockPos base,
	                                        Direction.Axis axis, boolean lit) {
		Direction across = axis == Direction.Axis.X ? Direction.EAST : Direction.SOUTH;
		BlockState frame = Blocks.DARK_OAK_LOG.getDefaultState();

		for (int w = -1; w <= WIDTH; w++) {
			for (int h = -1; h <= HEIGHT; h++) {
				boolean border = w == -1 || w == WIDTH || h == -1 || h == HEIGHT;
				BlockPos at = base.offset(across, w).up(h);
				if (border) {
					world.setBlockState(at, frame, net.minecraft.block.Block.NOTIFY_LISTENERS);
				} else if (lit) {
					world.setBlockState(at, ModBlocks.HOLLOW_PORTAL.getDefaultState()
							.with(HollowPortalBlock.AXIS, axis), net.minecraft.block.Block.NOTIFY_LISTENERS);
				} else {
					world.setBlockState(at, Blocks.AIR.getDefaultState(), net.minecraft.block.Block.NOTIFY_LISTENERS);
				}
			}
		}
		return base;
	}

	/**
	 * Tries to light a frame the player has built, from a block they clicked inside it.
	 *
	 * @return true if a portal was lit
	 */
	public static boolean tryIgnite(World world, BlockPos clicked) {
		// Answers on both sides. Finding a frame only reads blockstates, which the client has, and the
		// client needs the same answer we give: if it hears "not handled" it predicts a fire block in
		// the frame and shows a ghost flame until the server corrects it.
		for (Direction.Axis axis : new Direction.Axis[]{Direction.Axis.X, Direction.Axis.Z}) {
			BlockPos base = findFrameBase(world, clicked, axis);
			if (base != null) {
				if (world instanceof ServerWorld serverWorld) {
					buildFrame(serverWorld, base, axis, true);
				}
				return true;
			}
		}
		return false;
	}

	/** Locates the bottom-left interior block of a valid empty frame containing {@code inside}. */
	private static BlockPos findFrameBase(World world, BlockPos inside, Direction.Axis axis) {
		Direction across = axis == Direction.Axis.X ? Direction.EAST : Direction.SOUTH;
		for (int dw = 0; dw < WIDTH; dw++) {
			for (int dh = 0; dh < HEIGHT; dh++) {
				BlockPos base = inside.offset(across, -dw).down(dh);
				if (isValidFrame(world, base, across)) {
					return base;
				}
			}
		}
		return null;
	}

	private static boolean isValidFrame(World world, BlockPos base, Direction across) {
		for (int w = -1; w <= WIDTH; w++) {
			for (int h = -1; h <= HEIGHT; h++) {
				BlockPos at = base.offset(across, w).up(h);
				boolean border = w == -1 || w == WIDTH || h == -1 || h == HEIGHT;
				boolean corner = (w == -1 || w == WIDTH) && (h == -1 || h == HEIGHT);
				if (corner) {
					continue; // corners are not required, matching nether portal behaviour
				}
				if (border) {
					if (!world.getBlockState(at).isOf(Blocks.DARK_OAK_LOG)) {
						return false;
					}
				} else if (!world.getBlockState(at).isAir()) {
					return false;
				}
			}
		}
		return true;
	}

	// --- Director-driven placement ---

	/**
	 * Occasionally leaves a way in near a player who is already under pressure. Placed out of sight, in
	 * the dark, and left there permanently.
	 */
	public static BlockPos maybePlaceNear(ServerWorld world, net.minecraft.server.network.ServerPlayerEntity player,
	                                      Config cfg) {
		// Sixteen attempts, not forty. This runs inside a server tick and each attempt is a column
		// scan; forty misses was tens of thousands of block reads in one tick, every tick the roll
		// came up and found nothing.
		for (int attempt = 0; attempt < 16; attempt++) {
			double angle = world.random.nextDouble() * Math.PI * 2;
			double distance = 20 + world.random.nextDouble() * 44;
			int x = (int) (player.getX() + Math.cos(angle) * distance);
			int z = (int) (player.getZ() + Math.sin(angle) * distance);

			// Up to 64 blocks out is easily past what is loaded. Reading a block in an ungenerated
			// chunk generates it, synchronously, on the server thread.
			if (!world.isChunkLoaded(x >> 4, z >> 4)) {
				continue;
			}

			// Prefer a cave or wall face at the player's own depth. A portal cut into rock you are
			// standing next to is far more unsettling than a free-standing frame in the open, and it is
			// how you find one without looking for it.
			Site site = findWallSite(world, x, (int) player.getY(), z, cfg);
			if (site == null) {
				continue;
			}
			carveInto(world, site);
			buildFrame(world, site.base, site.axis, true);
			spreadTaint(world, site.base, site.axis);
			UnseenMod.LOGGER.debug("A way into the Hollow opened in a wall at {}", site.base);
			return site.base;
		}
		return null;
	}

	/** A frame position cut into a solid face, and the axis it should lie along. */
	private record Site(BlockPos base, Direction.Axis axis, Direction into) {
	}

	/**
	 * Looks for an air pocket — a cave, a tunnel, a room — with a solid wall beside it deep enough to
	 * hold a frame, scanning outward from the player's own elevation.
	 */
	private static Site findWallSite(ServerWorld world, int x, int startY, int z, Config cfg) {
		for (int dy = 0; dy <= 24; dy++) {
			for (int sign : new int[]{-1, 1}) {
				int y = startY + dy * sign;
				if (world.isOutOfHeightLimit(y) || world.isOutOfHeightLimit(y + HEIGHT + 1)) {
					continue;
				}
				BlockPos floor = new BlockPos(x, y, z);
				// Must be standing room, in the dark, on solid ground.
				if (!world.getBlockState(floor).isAir() || !world.getBlockState(floor.up()).isAir()) {
					continue;
				}
				if (!world.getBlockState(floor.down()).isSolidBlock(world, floor.down())) {
					continue;
				}
				if (world.getLightLevel(floor) > cfg.darkLightLevel) {
					continue;
				}
				for (Direction facing : new Direction[]{Direction.NORTH, Direction.SOUTH,
						Direction.EAST, Direction.WEST}) {
					if (isWall(world, floor, facing)) {
						Direction.Axis axis = facing.getAxis() == Direction.Axis.X
								? Direction.Axis.Z : Direction.Axis.X;
						// Sit the frame one block into the rock so it reads as cut into the face.
						return new Site(floor.offset(facing), axis, facing);
					}
				}
			}
		}
		return null;
	}

	/** True if there is enough solid rock in {@code facing} to bury a frame in. */
	private static boolean isWall(ServerWorld world, BlockPos floor, Direction facing) {
		int solid = 0;
		int total = 0;
		for (int h = 0; h < HEIGHT + 1; h++) {
			for (int depth = 1; depth <= 2; depth++) {
				BlockPos at = floor.up(h).offset(facing, depth);
				total++;
				BlockState state = world.getBlockState(at);
				if (state.isSolidBlock(world, at) && HollowTaintTarget.corruptible(state)) {
					solid++;
				}
			}
		}
		return total > 0 && solid >= total - 1;
	}

	/** Hollows out the frame volume so the portal sits flush in the face. */
	private static void carveInto(ServerWorld world, Site site) {
		Direction across = site.axis == Direction.Axis.X ? Direction.EAST : Direction.SOUTH;
		for (int w = -1; w <= WIDTH; w++) {
			for (int h = -1; h <= HEIGHT; h++) {
				world.setBlockState(site.base.offset(across, w).up(h),
						Blocks.AIR.getDefaultState(), net.minecraft.block.Block.NOTIFY_LISTENERS);
			}
		}
	}

	/**
	 * Rot caked onto a portal that generated inside a built structure.
	 * <p>
	 * {@link #spreadTaint} respects {@code canCorrupt}, which only allows natural stone, dirt and sand —
	 * deliberately, so creeping taint can never eat somebody's house. But a cottage cellar is stone
	 * brick, so that rule leaves a generated portal sitting in a clean tidy room with no rot on it at
	 * all, which is the one thing that was supposed to mark it as wrong. This is the worldgen-only
	 * exception: it encrusts the structure's own blocks once, at generation, and does not creep.
	 */
	public static void encrustTaint(net.minecraft.world.WorldAccess world, BlockPos base,
	                                Direction.Axis axis) {
		Direction across = axis == Direction.Axis.X ? Direction.EAST : Direction.SOUTH;
		Direction deep = axis == Direction.Axis.X ? Direction.SOUTH : Direction.EAST;
		for (int w = -2; w <= WIDTH + 1; w++) {
			for (int h = -2; h <= HEIGHT + 1; h++) {
				for (int d = -1; d <= 1; d++) {
					BlockPos at = base.offset(across, w).up(h).offset(deep, d);
					BlockState state = world.getBlockState(at);
					// Never eat the frame, the portal itself, or open space.
					if (state.isAir() || state.isOf(ModBlocks.HOLLOW_PORTAL)
							|| state.isOf(Blocks.DARK_OAK_LOG)) {
						continue;
					}
					int reach = Math.abs(w) + Math.abs(h) + Math.abs(d);
					if (world.getRandom().nextInt(Math.max(1, reach)) > 1) {
						continue;
					}
					world.setBlockState(at, ModBlocks.HOLLOW_TAINT.getDefaultState()
							.with(com.unseen.block.HollowTaintBlock.VIGOUR,
									com.unseen.block.HollowTaintBlock.MAX_VIGOUR),
							net.minecraft.block.Block.NOTIFY_LISTENERS);
				}
			}
		}
	}

	/**
	 * Seeds the rot around a portal. It is given full vigour here and creeps outward on its own from
	 * then on, so a portal left alone slowly eats the cave it sits in.
	 * <p>
	 * Takes {@link net.minecraft.world.WorldAccess} rather than {@code ServerWorld} so worldgen can call
	 * it too — a portal hidden under a cottage floor with no rot around it is just a doorway, and the
	 * rot is the thing that tells you the doorway is wrong.
	 */
	public static void spreadTaint(net.minecraft.world.WorldAccess world, BlockPos base,
	                               Direction.Axis axis) {
		Direction across = axis == Direction.Axis.X ? Direction.EAST : Direction.SOUTH;
		for (int w = -3; w <= WIDTH + 2; w++) {
			for (int h = -2; h <= HEIGHT + 2; h++) {
				for (int d = -2; d <= 2; d++) {
					BlockPos at = base.offset(across, w).up(h)
							.offset(axis == Direction.Axis.X ? Direction.SOUTH : Direction.EAST, d);
					BlockState state = world.getBlockState(at);
					if (!HollowTaintTarget.corruptible(state)) {
						continue;
					}
					// Denser at the mouth, ragged at the edges.
					int reach = Math.abs(w) + Math.abs(h) + Math.abs(d);
					if (world.getRandom().nextInt(Math.max(1, reach)) > 1) {
						continue;
					}
					world.setBlockState(at, ModBlocks.HOLLOW_TAINT.getDefaultState()
							.with(com.unseen.block.HollowTaintBlock.VIGOUR,
									com.unseen.block.HollowTaintBlock.MAX_VIGOUR),
							net.minecraft.block.Block.NOTIFY_LISTENERS);
				}
			}
		}
	}

	/** Indirection so the portal does not need to import the block class just for one predicate. */
	private static final class HollowTaintTarget {
		static boolean corruptible(BlockState state) {
			return com.unseen.block.HollowTaintBlock.canCorrupt(state);
		}
	}

	/**
	 * True when a frame based here would occupy nothing but air and grass.
	 * <p>
	 * Deliberately starts at {@code h = 0} rather than {@code -1}: the bottom border sits in the
	 * ground by design, and demanding that be empty too would refuse every natural landing. Assumes
	 * the X axis, which is the only axis return frames are built on.
	 */
	private static boolean clearFor(ServerWorld world, BlockPos base) {
		for (int w = -1; w <= WIDTH; w++) {
			for (int h = 0; h <= HEIGHT; h++) {
				BlockPos at = base.east(w).up(h);
				BlockState state = world.getBlockState(at);
				if (!state.isAir() && !state.isReplaceable()) {
					return false;
				}
			}
		}
		return true;
	}

	/**
	 * True when Immersive Portals is carrying travel through the frame this entity is standing in.
	 * <p>
	 * Links the frame on the spot if it is not linked yet. Worldgen portals arrive unlinked by
	 * necessity, and an entity standing in one is the first moment we have a {@code ServerWorld} to
	 * make the view entity with.
	 */
	private static boolean seamlessCovers(ServerWorld world, Entity entity) {
		if (!ImmersivePortalsBridge.available()) {
			return false;
		}
		BlockPos inside = entity.getBlockPos();
		BlockState state = world.getBlockState(inside);
		if (!state.isOf(ModBlocks.HOLLOW_PORTAL)) {
			// Feet can be a block below the portal on the way in; the head is still in it.
			inside = inside.up();
			state = world.getBlockState(inside);
			if (!state.isOf(ModBlocks.HOLLOW_PORTAL)) {
				return false;
			}
		}
		Direction.Axis axis = state.get(HollowPortalBlock.AXIS);
		return ImmersivePortalsBridge.createSeamless(world, frameBase(world, inside, axis), axis);
	}

	/** Walks down and back along the frame to the bottom-centre interior block. */
	private static BlockPos frameBase(ServerWorld world, BlockPos inside, Direction.Axis axis) {
		Direction across = axis == Direction.Axis.X ? Direction.EAST : Direction.SOUTH;
		BlockPos base = inside;
		while (world.getBlockState(base.down()).isOf(ModBlocks.HOLLOW_PORTAL)) {
			base = base.down();
		}
		while (world.getBlockState(base.offset(across, -1)).isOf(ModBlocks.HOLLOW_PORTAL)) {
			base = base.offset(across, -1);
		}
		return base;
	}

	/** True if a portal block already sits within a frame's reach of {@code landing}. */
	private static boolean hasPortalNear(ServerWorld world, BlockPos landing) {
		for (int dx = -WIDTH - 1; dx <= WIDTH + 1; dx++) {
			for (int dy = -1; dy <= HEIGHT + 1; dy++) {
				for (int dz = -WIDTH - 1; dz <= WIDTH + 1; dz++) {
					if (world.getBlockState(landing.add(dx, dy, dz)).isOf(ModBlocks.HOLLOW_PORTAL)) {
						return true;
					}
				}
			}
		}
		return false;
	}
}
